export const ProdukHukum = [
    {
      id: 1,
      title: "Kepgub No. 049/Kep.1305-Diskominfo/2018",
      description: "Government Chief Information Officer Pemerintah Daerah Provinsi Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2018,
      archiveDate: "2018-12-12",
    },
    {
      id: 2,
      title: "SE No. 016/73/DISKOMINFO",
      description: "Pembangunan/Pengembangan Aplikasi, Pemanfaatan Pusat Data dan Pengadaan Jaringan Internet/Intranet di Lingkungan Pemerintah Daerah Provinsi Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2020,
      archiveDate: "2018-12-13",
    },
    {
      id: 3,
      title: "SE No. 016/138/Diskominfo",
      description: "Pengadaan Jaringan Internet/Intranet Tahun 2021 di Lingkungan Pemerintah Daerah Provinsi Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2020,
      archiveDate: "2018-12-14",
    },
    {
      id: 4,
      title: "Kepgub No. 100.05/Kep.532-Diskominfo/2020",
      description: "Pelaksana Teknis Tim Koordinasi Sistem Pemerintahan Berbasis Elektronik Pemerintah Daerah Provinsi Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2020,
      archiveDate: "2018-12-15",
    },
    {
      id: 5,
      title: "SE No. 193/KOM.05.02.03/DISKOMINFO",
      description: "Pengelolaan Aplikasi di Lingkungan Pemerintah Daerah Provinsi Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2020,
      archiveDate: "2018-12-16",
    },
    {
      id: 6,
      title: "Perda No. 4 Tahun 2021",
      description: "Penyelenggaraan Komunikasi dan Informatika, Statistik dan Persandian",
      publisher: "Diskominfo Jawa Barat",
      year: 2021,
      archiveDate: "2018-12-17",
    },
    {
      id: 7,
      title: "SE No. 184/KU.01/Diskominfo",
      description: "Penganggaran Pembangunan Pengembangan Pemeliharaan Jaringan Local Area Network/Wireless Local Area Network Tahun 2022 di Lingkungan Pemerintah Daerah Provinsi Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2021,
      archiveDate: "2018-12-18",
    },
    {
      id: 8,
      title: "SK No. 2423/KPG.03.01.01/DISKOMINFO",
      description: "Tim Asesor Internal Pemantauan dan Evaluasi Sistem Pemerintahan Berbasis Elektronik Dinas Komunikasi dan Informatika Provinsi Jawa Barat Tahun 2022-2023",
      publisher: "Diskominfo Jawa Barat",
      year: 2022,
      archiveDate: "2018-12-19",
    },
    {
      id: 9,
      title: "Pergub No. 161 Tahun 2022",
      description: "Penyelenggaraan Sistem Pemerintahan Berbasis Elektronik di Lingkungan Pemerintah Daerah Provinsi Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2022,
      archiveDate: "2018-12-21",
    },
    {
      id: 10,
      title: "Kepgub No 102.05/Kep.215-Diskominfo/2023",
      description: "Tim Koordinasi SPBE Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2023,
      archiveDate: "2018-12-22",
    },
    {
      id: 11,
      title: "SP Sekda No. 2086/KPG.11.01/Diskominfo",
      description: "Tim Audit TIK",
      publisher: "Diskominfo Jawa Barat",
      year: 2023,
      archiveDate: "2018-12-23",
    },
    {
      id: 12,
      title: "Kepgub No 048/Kep.359-Diskominfo/2023",
      description: "Arsitektur SPBE Jabar 2023-2028",
      publisher: "Diskominfo Jawa Barat",
      year: 2023,
      archiveDate: "2018-12-24",
    },
    {
      id: 13,
      title: "Kepgub No 048/Kep.360-Diskominfo/2023",
      description: "Peta Rencana SPBE Jabar 2023-2028",
      publisher: "Diskominfo Jawa Barat",
      year: 2023,
      archiveDate: "2018-12-25",
    },
    {
      id: 14,
      title: "Kepgub No. 043/Kep.361-Diskominfo/2023",
      description: "Dewan Smart Province di Daerah Provinsi Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2023,
      archiveDate: "2018-12-26",
    },
    {
      id: 15,
      title: "Kepgub No. 043/Kep.398-Diskominfo/2023",
      description: "Kelompok Kerja Smart Province di Daerah Provinsi Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2023,
      archiveDate: "2018-12-27",
    },
    {
      id: 16,
      title: "Perda No. 7 Tahun 2023",
      description: "Penyelenggaraan Infrastruktur Digital di Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2023,
      archiveDate: "2018-12-28",
    },
    {
      id: 17,
      title: "SE No. 199/DISKOMINFO",
      description: "Panduan Implementasi Keamanan Siber untuk Instansi Pemerintah",
      publisher: "Diskominfo Jawa Barat",
      year: 2023,
      archiveDate: "2018-12-29",
    },
    {
      id: 18,
      title: "Kepgub No. 049/Kep.401-Diskominfo/2023",
      description: "Pedoman Manajemen Risiko Teknologi Informasi di Lingkungan Pemda",
      publisher: "Diskominfo Jawa Barat",
      year: 2023,
      archiveDate: "2018-12-30",
    },
    {
      id: 19,
      title: "Pergub No. 12 Tahun 2024",
      description: "Strategi Penguatan Infrastruktur Digital Pemerintah Daerah",
      publisher: "Diskominfo Jawa Barat",
      year: 2024,
      archiveDate: "2018-12-31",
    },
    {
      id: 20,
      title: "SE No. 250/DISKOMINFO",
      description: "Standar Pengelolaan Data dan Keamanan Informasi di Lingkungan Pemerintah",
      publisher: "Diskominfo Jawa Barat",
      year: 2024,
      archiveDate: "2019-01-01",
    },
    {
      id: 21,
      title: "Kepgub No. 102/Kep.500-Diskominfo/2024",
      description: "Tim Ahli Transformasi Digital Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2024,
      archiveDate: "2019-01-02",
    },
    {
      id: 22,
      title: "SE No. 310/KOMINFO",
      description: "Penguatan Digitalisasi Layanan Publik di Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2024,
      archiveDate: "2019-01-03",
    },
    {
      id: 23,
      title: "Kepgub No. 051/Kep.205-Diskominfo/2024",
      description: "Pedoman Implementasi Cloud Computing untuk Instansi Pemerintah Daerah",
      publisher: "Diskominfo Jawa Barat",
      year: 2024,
      archiveDate: "2019-01-04",
    },
    {
      id: 24,
      title: "Perda No. 9 Tahun 2024",
      description: "Kebijakan dan Strategi Pemerintahan Digital di Jawa Barat",
      publisher: "Diskominfo Jawa Barat",
      year: 2024,
      archiveDate: "2019-01-05",
    },
];

export const DokumenPerencanaan = [
  {
    id: 1,
    title: "Rencana Strategis Diskominfo 2023-2028",
    fileUrl: "/files/Renstra_Diskominfo_2023-2028.pdf",
  },
  {
    id: 2,
    title: "Master Plan Smart City 2025",
    fileUrl: "/files/MasterPlan_SmartCity_2025.pdf",
  },
  {
    id: 3,
    title: "Blueprint Transformasi Digital 2030",
    fileUrl: "/files/Blueprint_Digital_2030.pdf",
  },
  {
    id: 4,
    title: "Rencana Aksi Keamanan Siber 2024",
    fileUrl: "/files/Rencana_Aksi_Keamanan_2024.pdf",
  },
  {
    id: 5,
    title: "Peta Jalan AI Nasional 2025",
    fileUrl: "/files/PetaJalan_AI_2025.pdf",
  },
  {
    id: 6,
    title: "Roadmap Infrastruktur Digital 2035",
    fileUrl: "/files/Roadmap_Infrastruktur_2035.pdf",
  },
];

export const DokumenEvaluasi = [
  {
    id: 7,
    title: "Laporan Evaluasi Smart City 2022",
    fileUrl: "/files/Evaluasi_SmartCity_2022.pdf",
  },
  {
    id: 8,
    title: "Kajian Keamanan Data Publik 2021",
    fileUrl: "/files/Kajian_Keamanan_Data_2021.pdf",
  },
  {
    id: 9,
    title: "Audit Infrastruktur IT Pemda 2020",
    fileUrl: "/files/Audit_IT_Pemda_2020.pdf",
  },
];
